### ISSUE TITLE
Unsupported algorithm: http://www.w3.org/2001/04/xmldsig-more#sha256

### ISSUE THREAD

**Issue by shinnlok** [LoginRadius/go-saml#25]
**Describe the bug**
When checking out the repo and testing I noticed that the main example did not work.

**To Reproduce**
1. Implement https://github.com/LoginRadius/go-saml/blob/master/examples/response.go
2. `signedXMLErr &{signedxml: Unsupported Algorithm http://www.w3.org/2001/04/xmldsig-more#sha256 in SignatureMethod SIGNED_XML_ERROR}
`

**Expected behavior**
I expected a signed xml to be returned.

**Comment by mayankagwl** [comment]
@shinnlok 
 LoginRadius is also giving swags to people who will be contributing, so please make sure to read our blog and submit your info to get free goodies.

https://www.loginradius.com/engineering/page/hacktoberfest2020
