### ISSUE TITLE
Add support for reading the Key/Cert from the File

### ISSUE THREAD

**Issue by mayankagwl** [LoginRadius/go-saml#6]
Currently we are suppoting pem string fromat for Key/Cert, 
Add support for reading key/cert from the file,
Add fields in the Idp config to take up the filePath from the root directory to read from that perticular file.

**Comment by distributedlock** [comment]
I'll take this.

**Comment by mayankagwl** [comment]
@RanadeepPolavarapu 
And LoginRadius is also giving swags to people who will be contributing, so please make sure to read our blog and submit your info to get free goodies.

https://www.loginradius.com/engineering/page/hacktoberfest2020
